project:
  #type: book
  #output-dir: _book
#commented for website
 type: website
 output-dir: docs

website:
  title: "Home"
  sidebar:
    contents:
      - about.qmd
      - icon: github
        href: https://github.com/
    
format:
  html:
    theme: Solar
    css: styles.css
    code-fold: true
    code-tools: true

editor: visual

